### ISSUE TITLE
Actualizar el repositorio con la nueva version

### ISSUE THREAD

**Issue by GianfrancoMS** [Bruno125/Unofficial-Ups#3]
Cómo el título lo indica, ¿puedes actualizar el repositorio con la nueva versión de la app ?

**Comment by GianfrancoMS** [comment]
Podría ayudarte con el caching para que la app funcione offline. Se podría usar Room. Espero tu respuesta.

**Comment by Bruno125** [comment]
Hola! En este repo no está la última versión todavía. Te invitaré al repo privado. Ahí si uso Doom para algunas cosillas 😉

**Comment by carloncho155** [comment]
Alguien tiene la ultima apk?
